default_platform(:android)

platform :android do
  desc "Build para Play Tests"

  lane :build do
    UI.header "Building & signing apk..."
    
    gradle(task: "clean assemble")

    UI.success "apk ready!"
  end

  lane :beta do
    UI.header "Iniciando build de testes para Play Store"
    
    gradle(task: "clean assemble")  
    upload_to_play_store(track: 'beta', apk: "#{lane_context[SharedValues:: GRADLE_APK_OUTPUT_PATH]}")

    UI.success "Build realizado com sucesso! App disponível para testes na Play Store"
  end

  desc "Build para Google Play Store"
  lane :store do
    UI.header "Iniciando build de produção para Play Store"

    gradle(task: "clean assemble")

    UI.success "Build realizado com sucesso! App disponível na Play Store"
  end
end